# Generated by Django 5.2.8 on 2026-05-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_archive_service'),
        ('core', '0016_add_opsgate_service'),
    ]

    operations = [
    ]
