---
# public variables for deployment
project_name: "homelab"
username: "homelab"
home_path: "/home/{{ username }}"
site_path: "{{ home_path }}/site"
django_cache_location: "{{ site_path }}/cache"
global_python: python3.12
uv_path: "/usr/local/bin/uv"
venv_bin: "{{ site_path }}/venv/bin"
python: "{{ venv_bin }}/python"
default_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
app_port: 10010
django_settings_module: "config.settings.production"
systemd_unit_path: "/etc/systemd/system/{{ username }}.service"
granian_number_of_workers: 4
django_allowed_host: "127.0.0.1"

# Dynamic DNS configuration
ddns_domain: "wersdörfer.de"
ddns_subdomain: "home"
ddns_ttl: 300
ddns_log_dir: "{{ site_path }}/logs/ddns"
ddns_config_dir: "{{ site_path }}/config/ddns"
ddns_script_path: "{{ site_path }}/bin/ddns-home.sh"

# DNS Server configuration (Pi-hole)
dns_server_enabled: true
pihole_install_dir: "/opt/pihole"
pihole_config_dir: "/etc/pihole"
pihole_dnsmasq_dir: "/etc/dnsmasq.d"
pihole_log_dir: "/var/log/pihole"
# Get the internal IP dynamically, or set it explicitly
macmini_internal_ip: "{{ ansible_default_ipv4.address | default('192.168.178.50') }}"
dns_local_domain: "home.{{ ddns_domain }}"
# Service port allocations for future services
service_ports:
  homelab: 10010
  # Future services can be added here
  # monitoring: 10011
  # paperless: 10012