---
# public variables for deployment
project_name: "homelab"
username: "homelab"
home_path: "/home/{{ username }}"
site_path: "{{ home_path }}/site"
django_cache_location: "{{ site_path }}/cache"
global_python: python3.12
uv_path: "/usr/local/bin/uv"
venv_bin: "{{ site_path }}/venv/bin"
python: "{{ venv_bin }}/python"
default_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
app_port: 10010
django_settings_module: "config.settings.production"
systemd_unit_path: "/etc/systemd/system/{{ username }}.service"
granian_number_of_workers: 4
django_allowed_host: "127.0.0.1"

# Dynamic DNS configuration
ddns_domain: "wersdörfer.de"
ddns_subdomain: "home"
ddns_ttl: 300
ddns_log_dir: "{{ site_path }}/logs/ddns"
ddns_config_dir: "{{ site_path }}/config/ddns"
ddns_script_path: "{{ site_path }}/bin/ddns-home.sh"